# Generated by Django 2.2.3 on 2019-07-15 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacion_Academica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('institucion', models.CharField(blank=True, max_length=100, null=True)),
                ('abrebiacion', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='img/maestros/')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
                ('formacion', models.ManyToManyField(blank=True, to='itic.Formacion_Academica', verbose_name='Formacion Academica')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='noticias/')),
                ('descripcion', tinymce.models.HTMLField(blank=True, max_length=300, null=True)),
                ('body', tinymce.models.HTMLField(blank=True, null=True)),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('actualizado', models.DateField(auto_now=True, null=True)),
                ('tags', models.ManyToManyField(to='itic.Tag', verbose_name='Tags')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='formacion_academica',
            name='nivel',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='itic.Nivel'),
        ),
    ]
