# Generated by Django 2.2.3 on 2019-07-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0002_archivo_proceso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('clave', models.CharField(blank=True, max_length=18, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
