# Generated by Django 2.2.3 on 2019-07-20 20:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0003_matter'),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='actualizado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='horas_escritas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='horas_practicas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 7, 20, 20, 23, 30, 823756, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
