# Generated by Django 2.2.3 on 2019-07-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0004_auto_20190720_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='archivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='itic.Archivo'),
        ),
    ]
