# Generated by Django 2.2.3 on 2019-07-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0005_matter_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
