# Generated by Django 2.2.3 on 2019-07-26 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0007_matter_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='matter',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='itic.Semestre'),
        ),
    ]
