# Generated by Django 2.2.3 on 2019-07-26 20:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0008_auto_20190726_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=1000, null=True),
        ),
    ]
